trigger:
- master

pr:
- master  

jobs:

- job: build
  displayName:  'Test using '
  pool:
    vmImage: 'Ubuntu 16.04'
    
  strategy:
    matrix:
      pip-gcc4:
        gccVersion: '4.9'
        MPI_INSTALL: '1'
        installWithPip: 'true'        
      conda--gcc8:
        gccVersion: '8'
        MPI_INSTALL: '1'
        installWithPip: 'false'
      nompi-conda-gcc5:
        gccVersion: '5'
        MPI_INSTALL: '0'
        installWithPip: 'false'
      conda-gcc7:
        gccVersion: '7'
        MPI_INSTALL: '1'
        installWithPip: 'false'

  timeoutInMinutes: 120
  steps:
  - task: Docker@1
    displayName: "Build container"
    inputs:
      command: 'build'
      arguments:
        --build-arg gccVersion=$(gccVersion)
        --build-arg installWithPip=$(installWithPip)
        --build-arg MPI_INSTALL=$(MPI_INSTALL)
